import { useRouter } from 'next/router'
import React from 'react'
import { Inter } from 'next/font/google'
import styles from './Article.module.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Article() {

	const router = useRouter()

	const handleClick = () => {
		router.push('/')
	}

	return (
		<>
			<Head>
				<title>{ router.query.article }</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<div className={`${ styles.main } ${ inter.className }`}>
				<h1>{ router.query.article }</h1>
				<button onClick={ handleClick }>Return to home</button>
			</div>
		</>
	)
}
